server:
  port: 0

spring:
  application:
    name: payment-service
  jpa:
    database: "mysql"
    show-sql: "true"
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true

  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/payment?useSSL=false&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true"
    username: "root"
    password: "0000"

  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
      group-id: "returnedGroupId"
    topic:
      name: "returned"
